# Generated by Django 5.1 on 2024-08-31 16:43

from django.db import migrations


def seed_data(apps, schema_editor):
    User = apps.get_model("backend", "User")
    BlogPost = apps.get_model("backend", "BlogPost")

    # Create a sample user
    user, created = User.objects.get_or_create(
        username="admin",
        defaults={"email": "admin@example.com", "is_staff": True, "is_superuser": True},
    )
    if created:
        user.set_password("password")
        user.save()

    # Create sample blog posts
    BlogPost.objects.get_or_create(
        title="First Blog Post",
        content="This is the content of the first blog post.",
        author=user,
    )

    BlogPost.objects.get_or_create(
        title="Second Blog Post",
        content="This is the content of the second blog post.",
        author=user,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
