import type { Metadata } from "next";
import { Inter } from "next/font/google";

import CatalystHeader from "@/common/components/CatalystHeader/CatalystHeader";
import NavigationItem, { NavigationListItem } from "@/common/components/NavigationHeader/NavigationItem";
import { NavigationMenuLink } from "@/common/ui/navigation-menu";
import { MicroblogProviderStack } from "@/common/contexts/MicroblogProviderStack";

const inter = Inter({ subsets: ["latin"] });

import "./globals.css";
import '@mdxeditor/editor/style.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <MicroblogProviderStack >
        {children}
        </MicroblogProviderStack>
      </body>
    </html>
  );
}
