# Add database
# Add backend image
# add frontend image

services:

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: uvicorn backend.asgi:application

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=panda
      - POSTGRES_PASSWORD=panda
      - POSTGRES_DB=microblog
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    # driver: local
